# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - ms-ads-ranking

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # remove cache: 'pnpm' because pnpm isn't available yet and will cause errors

      - name: Enable corepack and prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Build frontend assets
        run: pnpm run build
        env:
          BASE_URL: /assets

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create virtual environment and install server dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r pizzaz_server_python/requirements.txt

      - name: Prepare deployment artifact
        run: |
          mkdir -p deployment
          cp -r pizzaz_server_python deployment/pizzaz_server_python
          cp -r assets deployment/assets
          cp pizzaz_server_python/requirements.txt deployment/requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deployment/
      

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1264B02F95CE490E8B9C39202D263AC2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_387A49B47D0B4048A2B51C447C51F62E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_401B13995F6045769C23ED6C678EF5D9 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'ms-ads-ranking'
          slot-name: 'Production'



